# NOASYNCIO
# NOANYIO - don't run it with substitutions
import anyio
import trio

try:
    ...
except trio.Cancelled:  # ASYNC103: 7, "trio.Cancelled"
    ...
except (
    anyio.get_cancelled_exc_class()  # ASYNC103: 4, "anyio.get_cancelled_exc_class()"
):
    ...
except:  # safe
    ...

try:
    ...
except (
    anyio.get_cancelled_exc_class()  # ASYNC103: 4, "anyio.get_cancelled_exc_class()"
):
    ...
except trio.Cancelled:  # ASYNC103: 7, "trio.Cancelled"
    ...
except:  # safe
    ...

try:
    ...
except (
    anyio.get_cancelled_exc_class()  # ASYNC103: 4, "anyio.get_cancelled_exc_class()"
):
    ...
except:  # safe ?
    ...

try:
    ...
except trio.Cancelled:  # ASYNC103: 7, "trio.Cancelled"
    ...
except:  # safe ?
    ...

# Check we get the proper suggestion when both are imported
try:
    ...
except BaseException:  # ASYNC103_anyio_trio: 7, "BaseException"
    ...

try:
    ...
except:  # ASYNC103_anyio_trio: 0, "bare except"
    ...
